### ISSUE TITLE
ScrambleDB Error Handling

### ISSUE THREAD

**Issue by franziskuskiefer** [cryspen/atlas#2]
Let's add this in a followup (for all the TODOs).
You can introduce a `CurveError` `Error` variant and implement a `From<p256::Error>` for it. Then we can replace all the `unwrap`s with `?`.

_Originally posted by @franziskuskiefer in https://github.com/cryspen/atlas/pull/1#discussion_r1282230076_

**Comment by jschneider-bensch** [comment]
Duplicate of #15 .
